FROM bellsoft/liberica-openjdk-alpine:23
WORKDIR /app
# curl, чтобы Docker мог проверять "здоровье" сервиса
RUN apk add --no-cache curl
COPY build/libs/*-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]