server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/v1/users/$\{segment} # API Versioning & Path Mapping
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/users


          # 2. Маршрут для Swagger (БЕЗ RewritePath)
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /webjars/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
